title: Best Blog
author: Me
email: noyb@fu.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a test

# social links
github_username:  alejandromango # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
